export const GET_FACULTY_ALL = "GET_FACULTY_ALL";
export const GET_FACULTY_DEPTWISE = "GET_FACULTY_DEPTWISE";
export const GET_FACULTY_INDIVIDUAL = "GET_FACULTY_INDIVIDUAL";

export const GET_ADMISSION_PROCEDURE_POINTS = "GET_ADMISSION_PROCEDURE_POINTS";
export const GET_ADMISSION_PROGRAMMES_DETAILS = "GET_ADMISSION_PROGRAMMES_DETAILS";
export const GET_FEE_STRUCTURE_DETAILS = "GET_FEE_STRUCTURE_DETAILS";

export const GET_ANNOUNCEMENTS = "GET_ANNOUNCEMENTS";
export const GET_ACADEMIC_NEWS = "GET_ACADEMIC_NEWS";
export const GET_AWARDS = "GET_AWARDS";
